### PR TITLE
GameEngine: Changed coordinates to points

### PR DESCRIPTION
**Pull request by DorianRec**
Changed coordinates to points, such that
the project is more consistent.

### CODE REVIEW

**Comment by jotoh98** [comment]
This has to be heavily tested in serialization, deserialization and overall runs.

**Review by jotoh98 — COMMENTED** [review]
This has to be heavily tested in serialization, deserialization and overall runs.

**Comment by DorianRec** [comment]
> This has to be heavily tested in serialization, deserialization and overall runs.

This changes should not do any semantically changes.
Nevertheless, almost every test we wrote, tests the gameengine and gamemanager, thus I dont think, that I added bugs.

**Review by jotoh98 — APPROVED** [review]
As long as you tested serialization and so on and so forth, feel free to merge

**Pull request merged**
