### PR TITLE
bring geometry angle in correct order (left, center, right)

### LINKED ISSUE #150: Reorder GeometryAngle to conform intuitive Linestring thinking
Reorder center,left, right 
to
right, center, left OR left,center,right

### PR DESCRIPTION
**Pull request by jotoh98**
Reordered the geometry angle's coordinates. Now the two resulting half-lines face in the correct direction. 

Fixes #150

### CODE REVIEW

**Comment by 1-alex98** [comment]
tests fail and btw do we not maybe just wanna leave it the way it is

**Comment by 1-alex98** [comment]
Fix Ci

**Comment by 1-alex98** [comment]
This needs to be checked again after all strategies are on master

**Review by DorianRec — APPROVED** [review]

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
hint strategy is still not merged... and the re factor needs to be done there as well

**Pull request closed without merging**
