### PR TITLE
added rounded display of numeric values

### LINKED ISSUE #293: Numeric values not rendered rounded to setting decimal place
The statistics table doesn't display the values rounded to the decimal place set in the settings

### PR DESCRIPTION
**Pull request by jotoh98**
Fixes #293

### CODE REVIEW

**Comment by DorianRec** [comment]
Why is the Statistics rendered with ",", but the rest is not ?
Bildschirmfoto 2020-03-31 um 15 39 30

**Comment by jotoh98** [comment]
Feature was not implemented completely. Added implementation were I found it missing except for user input to display full input and prevent misunderstandings.
Also added a setting in the settings page to control the programs localization. Maybe @DorianRec could add i18n text for all locales? I promise, it's a fast task ;)

**Review by DorianRec — DISMISSED** [review]
Unfortunately, some functionality is gone now.
Starting the program causes no Searcher/Hider/GameEngine being pre-selected.
Is this intendet?

**Review by DorianRec — DISMISSED** [review]

**Review by DorianRec — APPROVED** [review]

**Review by DorianRec — DISMISSED** [review]
Bildschirmfoto 2020-04-02 um 13 36 08
Unfortunately, the statistics plot is pretty hard to read.

**Review by DorianRec — DISMISSED** [review]
Unfortunately, when starting the program (with searcher, hider and gameEngine selected **loaded, with were pre-selected**), the initialization-button (with the text "..") causes the program to crash.

**Review by DorianRec — DISMISSED** [review]
I am not sure, if this represents the wished behaviour:
(I set local to en_US):

Bildschirmfoto 2020-04-02 um 19 55 58

Unfortunately, also in the multiple runs, i can see both, "," and "."

**Review by DorianRec — APPROVED** [review]
looks tasty

**Pull request merged**
