### PR TITLE
bad hint hider added, sometimes breaks the StrategyFromPaper

### LINKED ISSUE #347: MinimumRectangleStrategy breaks HalfPlaneAdapter_FixedTreasure
Sometimes the MinimumRectangleStrategy from the branch ImprovedStrategyFromPaper (or master, when #346 gets merged) breaks the HalfPlaneAdapter_FixedTreasure:

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Operation does not support GeometryCollection arguments
	at org.locationtech.jts.geom.Geometry.checkNotGeometryCollection(Geometry.java:1803)
	at org.locationtech.jts.geom.Geometry.difference(Geometry.java:1414)
	at com.treasure.hunt.strategy.hider.impl.GameField.commitPlayerMovement(GameField.java:212)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:69)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:37)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:15)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:126)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:116)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:178)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:275)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

### PR DESCRIPTION
**Pull request by rukemn**
counterstrategy against StrategyFromPaper,

might be factored out later into JTSUtils, to judge whether or not a specific hint is bad or not

sometimes breaks the StrategyFromPaper with the known bug "Somehow there was no basic transformation found for this rectangle and hint. This is impossible." 

in method "strategyFromPaper.RoutinesFromPaper.getBasicTransformation"

Fixes #347

### CODE REVIEW

**Review by DorianRec — DISMISSED** [review]
This is not implemented yet ^^
Did you forget to push, or did your push fail ?

**Review by DorianRec — DISMISSED** [review]
@bsen @rukemn 
Unfortunately, for some reason, I got an exception:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.LastHintBadSubroutine.lastHintBadSubroutine(LastHintBadSubroutine.java:356)
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.StrategyFromPaper.move(StrategyFromPaper.java:115)
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.StrategyFromPaper.move(StrategyFromPaper.java:34)
	at com.treasure.hunt.game.GameEngine.searcherMove(GameEngine.java:139)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:109)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:177)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:274)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Review by DorianRec — DISMISSED** [review]

**Comment by DorianRec** [comment]
I will test this, when the StrategyFromPaper is fixed,
but nevertheless, the BadHintHider seems to work fine! 💪

**Comment by rank-and-file** [comment]
Seems to work with the current implementation of StrategyFromPaper
Maybe use different name for the Hider since BadHalfPlaneHintHider already exists

**Review by DorianRec — APPROVED** [review]
Seems to work fine

**Review by DorianRec — DISMISSED** [review]
Simulating agains MinimumRectangleStrategy and HalfplaneAdapter_FixedTreasure gave me the below exception.
If it is not intended, that MinimumRectangleStrategy plays agianst HalfplaneAdapter_FixedTreasure, please return a LOG_LABEL_EVENT like you did in the BadHintHider! ;)

14:31:59.807 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - generating 360 hints of size 180.0
14:31:59.850 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - current possibleArea size 31362.36339821023
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.treasure.hunt.utils.JTSUtils.isBadHint(JTSUtils.java:399)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.eval(StatisticalHider.java:121)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:78)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:37)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:15)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:126)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:116)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:178)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:275)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Review by DorianRec — APPROVED** [review]

**Review by DorianRec — CHANGES_REQUESTED** [review]
Simulating MinimumRectangleStrategy vs HalfplaneAdapter_FixedHider throws an exception:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.treasure.hunt.utils.JTSUtils.isBadHint(JTSUtils.java:402)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.eval(StatisticalHider.java:121)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:78)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:37)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:15)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:126)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:116)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:178)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:275)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by rukemn** [comment]
This bug was occurring because MinimumRectangleStrategy is not adding a "current rectangle" GeometryItem to its Move. Therefore the StatisticalHider can't extract it.

The implementation is now fixed to be more robust for such cases

**Review by DorianRec — APPROVED** [review]
works

**Pull request merged**
